### ISSUE TITLE
Specifying additional HTTP headers

### ISSUE THREAD

**Issue by bilogic** [optimalstrategy/sms_forwarder_app#13]
Hi, possible to enter header `Authorization: Bearer <token>` when calling a HTTP endpoint?

```
curl \
    --request POST \
    --header "Content-Type: application/json" \
    --header "Authorization: Bearer *************" \
    --data '{"json": "data"}' \
    https://example.com/url
```

**Comment by optimalstrategy** [comment]
No, it's not currently possible to specify custom headers, but that's an easy feature to implement. I'll look into this when I get some free time.

**Comment by bilogic** [comment]
Looking forward to it! Thank you!

**Comment by optimalstrategy** [comment]
@bilogic Please see the latest [release](https://github.com/optimalstrategy/sms_forwarder_app/releases/tag/v1.6.0). You can now specify custom HTTP headers similarly to the JSON payload and URI params:

<img src="https://user-images.githubusercontent.com/17456182/143664213-190186f6-d788-45e0-b78e-20ecd464f575.png" width="250"> <img src="https://user-images.githubusercontent.com/17456182/143664217-c6acf27e-385d-4abc-9726-55f99c174c48.png" width="250">

.

**Comment by bilogic** [comment]
hey man thanks! Already upgraded and testing it. 

Seems that a Authorization cannot be updated/removed after it is added. 
I can update or remove it, but after closing the app and starting it again, the header is back. Any idea?

**Comment by bilogic** [comment]
Ok, false alarm, I missed the `save` button. Thank you!

**Comment by optimalstrategy** [comment]
Yeah, I think it's not obvious that you must press the button in order for the changes to be recorded. Do you think it would be better if the app had autosave?

**Comment by bilogic** [comment]
@optimalstrategy hmm, given the current UI, I guess what makes more sense is, if the data is dirty, pop up a prompt to save or discard when pressing the back arrow on `Http Callback Settings`

**Comment by optimalstrategy** [comment]
@bilogic I like this idea, thank you! I'll open an issue for this one and implement it when I get a chance.
