### ISSUE TITLE
Better HTTP security

### ISSUE THREAD

**Issue by bilogic** [optimalstrategy/sms_forwarder_app#2]
Hi,

It is more "secured" to use POST instead of GET in that the parameters are not logged by HTTP servers. It is also helpful to allow specifying custom key-value pairs such as API tokens for accessing APIs.

Great work!

**Comment by optimalstrategy** [comment]
Hi,

Thank you for the kind words!

I don't have time to implement all of your suggestions immediately, but I'll probably get to it sometime during this week.

**Comment by optimalstrategy** [comment]
@bilogic I've implemented your suggestions. The new version of the app is available here: https://github.com/optimalstrategy/sms_forwarder_app/releases/tag/1.3.0.

**Comment by bilogic** [comment]
@optimalstrategy thanks! will test it in a bit!
