### ISSUE TITLE
Ideas: Testing of endpoints and others

### ISSUE THREAD

**Issue by bilogic** [optimalstrategy/sms_forwarder_app#7]
Hi,

Some ideas after using this for a while:

1. When entering HTTP/Telegram endpoints, can have a button to immediately send a test message?
2. Can it run on boot?
3. It sometimes doesn't forward SMSs, not sure if this was because I did a reboot or it was killed, does the listening in background solves the issue?
4. Update notifications, maybe can consider releasing it on f-droid, or have the app check a link on this repo and show a notification on startup

Thank you!

**Comment by optimalstrategy** [comment]
Hi,

Thank you using my app and your suggestions. Addressing every point,

1. Sure, I'll look into this.
2. Possibly, yes.
3. Have you been using the [latest version](https://github.com/optimalstrategy/sms_forwarder_app/releases/tag/v1.4.0) (1.4.0)? Prior to v1.4.0, the app didn't have background forwarding. I've tested v1.4.0 in the emulator and on my own phone, and it's been working fine for the past two weeks. Although, it won't restart if it gets killed by android for good (e.g. if you run out of RAM/battery and the OS decides to kill everything non-essential).
4. I'll look into F-droid and checking for updates. If publishing an app is simple enough, I might do it soon™. 

Having said all of this, I am pretty busy with my college right now (final semester), so I can't promise getting back to this immediately.

**Comment by bilogic** [comment]
Hi, I fully understand this is on a best effort basis.

3. I have been using 1.3.0 until yesterday. I haven't been able to get 1.4.0 to work on HTTP yet. (I just did an upgrade, earlier settings was still there)

Thank you.

**Comment by bilogic** [comment]
> 1. I have been using 1.3.0 until yesterday. I haven't been able to get 1.4.0 to work on HTTP yet. (I just did an upgrade, earlier settings was still there)

I traced my HTTP logs, in 1.4.0, `dateSent=null`, that threw an exception in my code, so 1.4.0 looks good so far. Thank you.

**Comment by optimalstrategy** [comment]
@bilogic I've implemented launch on boot, and quick-n-dirty update checking and forwarder testing.

1) The app should now automatically launch on on boot; you can configure this behavior in the new settings screen.
2) The app update status is displayed in the app bar:
![image](https://user-images.githubusercontent.com/17456182/112435918-c2658a80-8d1b-11eb-88f7-aca80ceafca0.png)
3) This is not exactly what you wanted, but there's now a button to test all forwarders in the settings screen as (1). A single button was faster to implement, so I figured that something is better than nothing.
    - Grey = Forwarder is not configured, 
    - Green = Received an HTTP status code >= 200 and < 400,
    - Red = Everything else, including failed requests.
![image](https://user-images.githubusercontent.com/17456182/112436619-4a4b9480-8d1c-11eb-9458-a77bec6b9df4.png)

**Comment by bilogic** [comment]
Wow, I just tested, all points fulfilled! (I assumed the version check works)

Thank you @optimalstrategy !
